- name: Ansible Playbook for reproducibly configuring my Raspberry Pi
  hosts: pis
  remote_user: pi
  vars:
    - youtubedl_executable_path: "/usr/local/bin/youtube-dl"
    - youtubedl_update: true
  tasks:
    - name: update-upgrade Setup
      include: tasks/update-upgrade.yml
    - name: youtube-dl
      include: tasks/youtube-dl.yml
    - name: yt-dlp
      include: tasks/yt-dlp.yml
    - name: ffmpeg
      include: tasks/ffmpeg.yml
    - name: omx
      include: tasks/omx.yml