- name: Ansible Playbook for reproducibly configuring my Raspberry Pi
  hosts: pis
  remote_user: pi
  vars:
    - youtubedl_executable_path: "/usr/local/bin/youtube-dl"
    - youtubedl_update: true
    - pyenv_global: "{{ pyenv_python37_version }} system"
    - nodejs_version: 18.18.2
  tasks:
    - name: update-upgrade Setup
      include: tasks/update-upgrade.yml
    - name: yt-dlp
      include: tasks/yt-dlp.yml
    # - name: ffmpeg
    #   include: tasks/ffmpeg.yml
    - name: media-players
      include: tasks/media-players.yml
    - name: tmux
      include: tasks/tmux.yml
    - name: python
      include: tasks/pyenv-python.yml
    # - name: nodejs
    #   include: tasks/nodejs.yml
    - name: log2ram
      include: tasks/log2ram.yml
