- name: "Download & Install FFMPEG"
  become: True
  unarchive:
    src:  https://github.com/ffbinaries/ffbinaries-prebuilt/releases/download/v4.4.1/ffmpeg-4.4.1-linux-armel-32.zip
    dest: /usr/local/bin
    remote_src: yes
    mode: a+rx
