  - name: Run the equivalent of "apt-get update" as a separate step
    become: True
    apt:
      update_cache: true
      cache_valid_time: 3600
  - name: Update all packages to the latest version
    become: True
    apt:
      upgrade: dist