

# https://cloudcone.com/docs/article/how-to-install-python-3-10-on-debian-11/
- name: "Download & Install pyenv deps"
  become: True
  apt:
    update_cache: true
    name:
      - git
      - liblzma-dev
      - libbz2-dev
      - libffi-dev
      - libssl-dev
      - libncurses-dev
      - libreadline-dev
      - libsqlite3-dev

- name: "Download & Install pyenv"
  shell: |
    curl https://pyenv.run | bash
    echo 'export PYENV_ROOT="$HOME/.pyenv"' >> ~/.bashrc
    echo 'command -v pyenv >/dev/null || export PATH="$PYENV_ROOT/bin:$PATH"' >> ~/.bashrc
    echo 'eval "$(pyenv init -)"' >> ~/.bashrc
    source ~/.bashrc
  args:
    executable: /bin/bash

# - name: "Download & Install pyenv python 3.10"
#   shell: |
#     source ~/.bashrc
#     pyenv install 3.10
#     pyenv global 3.10
#   args:
#     executable: /bin/bash

