---
- name: Install SABnzbd dependencies
  apt:
    name:
      - python3
      - python3-pip
      - python3-dev
      - python3-venv
      - git
      - build-essential
      - libffi-dev
      - libssl-dev
      - libxml2-dev
      - libxslt1-dev
      - par2
      - unzip
      - unrar-free
    state: present
    update_cache: yes

- name: Create SABnzbd directory
  file:
    path: "/opt/sabnzbd"
    state: directory
    mode: '0755'

- name: Configure Git to allow cloning in /opt/sabnzbd
  command:
    cmd: git config --global --add safe.directory /opt/sabnzbd
  changed_when: true

- name: Clone SABnzbd repository
  git:
    repo: "https://github.com/sabnzbd/sabnzbd.git"
    dest: "/opt/sabnzbd"
    version: master

- name: Create virtual environment
  command:
    cmd: python3 -m venv /opt/sabnzbd/venv
    creates: /opt/sabnzbd/venv

- name: Install Python requirements in virtual environment
  pip:
    requirements: "/opt/sabnzbd/requirements.txt"
    virtualenv: "/opt/sabnzbd/venv"
    state: present

- name: Create SABnzbd service user
  user:
    name: sabnzbd
    system: yes
    create_home: yes
    home: /home/sabnzbd
    shell: /usr/sbin/nologin

- name: Create SABnzbd config directory
  file:
    path: /home/sabnzbd/.sabnzbd
    state: directory
    owner: sabnzbd
    group: sabnzbd
    mode: '0755'

- name: Create log directory
  file:
    path: /var/log/sabnzbd
    state: directory
    owner: sabnzbd
    group: sabnzbd
    mode: '0755'

- name: Create log files
  file:
    path: "{{ item }}"
    state: touch
    owner: sabnzbd
    group: sabnzbd
    mode: '0644'
  loop:
    - /var/log/sabnzbd/sabnzbd.log
    - /var/log/sabnzbd/sabnzbd.error.log

- name: Create config directory
  file:
    path: /home/sabnzbd/.sabnzbd
    state: directory
    owner: sabnzbd
    group: sabnzbd
    mode: '0755'

- name: Create systemd service file
  template:
    src: sabnzbd.service.j2
    dest: /etc/systemd/system/sabnzbd.service
    mode: '0644'

- name: Start and enable SABnzbd service
  systemd:
    name: sabnzbd
    state: started
    enabled: yes
    daemon_reload: yes
- name: Check if mount point exists and set sabnzbd permissions
  block:
    - name: Check if directory exists
      stat:
        path: /mnt/external
      register: mount_check

    - name: Set sabnzbd ownership and permissions
      file:
        path: /mnt/external
        owner: sabnzbd
        group: sabnzbd
        mode: '0755'
        recurse: yes
      when: mount_check.stat.exists
      register: perm_result

    - name: Display status message
      debug:
        msg: "Directory does not exist at /mnt/external"
      when: not mount_check.stat.exists

  rescue:
    - name: Display error message
      debug:
        msg: "Failed to set permissions. Please ensure sabnzbd user and group exist."